project:
  type: website

website:
  favicon: images/favicon-32x32.png
  google-analytics: G-GK3FJRW2VX
  cookie-consent:
    type: express
    style: headline
    palette: dark
  site-url: https://happy-valley-arts.com
  page-footer:
    left: "The Arts in Happy Valley | 2024"
    right:
      - text: "{{< iconify memory:email >}} Subscribe to the Newsletter"
        href: "https://magic.beehiiv.com/v1/b6ade0aa-ce61-466f-a5af-1088cd62508e"
      - text: "{{< iconify memory:coffee >}} Support my work with a coffee"
        href: https://www.buymeacoffee.com/aferguson93
  title: "The Arts in Happy Valley"
  description: A blog dedicated to the arts in Happy Valley, Pennsylvania.
  twitter-card: true
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
  sidebar:
    logo: images/AHV-logo1.png
format:
  html:
    theme: lux
    css: styles.css



