project:
  type: website

website:
  google-analytics: G-GK3FJRW2VX
  site-url: https://happy-valley-arts.com
  page-footer:
    left: "The Arts in Happy Valley | 2024"
    right:
      - text: "{{< iconify memory:email >}} Subscribe to the Newsletter"
        href: "https://magic.beehiiv.com/v1/b6ade0aa-ce61-466f-a5af-1088cd62508e"
      - text: "{{< iconify memory:coffee >}} Support my work with a coffee"
        href: https://www.buymeacoffee.com/aferguson93
  title: "The Arts in Happy Valley"
  description: A blog dedicated to the arts in Happy Valley, Pennsylvania.
  navbar:
    logo: "images/AHV-logo1.png"
    right:
      - text: Blog
        href: blog.qmd
      - icon: rss
        href: blog.xml
format:
  html:
    theme: lux
    css: styles.css



